- docs/CODEOWNERS
All team members can review and merge PRs.
This is less organised.
Require specific users(maintainers and owner) to approve PRs before they can be merged to ensure accountability when managing the team repo.
> Protect repo with CODEOWNERS file

- src/main/java/seedu/duke/command/BadCommandException.java
- src/main/java/seedu/duke/command/CommandParser.java
- src/test/java/seedu/duke/command/CommandParserTest.java
This closes #15 .
1. Added a `command` package to WellNus
2. Added CommandParser logic which processes string representing user input
- `parseuserInput` logically divides it into argument-payload pairs via a `HashMap` 
- `getMainArgument` provides a useful utility for any caller to get the main argument (action) from a command input string
3. Added in unit tests for public CommandParser methods, accounting for many adversarial test cases
> Add Command Parser feature

- src/main/java/seedu/duke/command/CommandParser.java
- src/test/java/seedu/duke/command/CommandParserTest.java
This fixes #40 
- Fixed the bug causing empty inputs not being detected and throwing the appropriate error
- Added more unit tests to check that the guard clause works as expected
> Fix getMainException unthrowable error

- src/main/java/seedu/duke/manager/Manager.java
This fixes #50 and closes #51 
- Changed how Manager is constructed to prevent crashes
- Added some documentation explaining sample implementation for the setter functions
`setSupportedCommands` and `setSupportedManagers` is intentionally left as abstract to force developers to remember to properly populate values in the attribute.
> Fix Manager bug and improve its usability

- docs/AboutUs.md
This fixes #37.
- Fixed picture not rendering properly issue
- Added picture labels that will show the developer names if the picture fails to render
> Fix AboutUs picture rendering bug

- src/main/java/seedu/duke/manager/Manager.java
There is a dangling method referencing the depreciated `supportedFeatures` attribute. This should be depreciated.
This affects #65 .
> Remove dangling supportedFeatures method

- src/main/java/wellnus/atomichabit/command/UpdateCommand.java
- src/test/java/wellnus/atomichabit/AtomicHabitTest.java
Minor change to add .trim() to the payload, allowing trailing spaces not to be thrown by NumberFormatException. Add assertion and logging
> UpdateHabit Assertion and Logging

- src/main/java/wellnus/atomichabit/command/AddCommand.java
- src/main/java/wellnus/atomichabit/command/ExitCommand.java
- src/main/java/wellnus/atomichabit/command/ListCommand.java
- src/main/java/wellnus/atomichabit/command/UpdateCommand.java
- src/main/java/wellnus/atomichabit/feature/AtomicHabitManager.java
- src/test/java/wellnus/atomichabit/AtomicHabitTest.java
Wrongly required the feature keyword `hb` in front of all commands given in atomic habits' `Manager` user interface.
Remove this requirement so it matches behaviour in other features, as users would expect.
> Fix atomic habit commands

- src/main/java/wellnus/common/MainManager.java
- src/main/java/wellnus/reflection/ExitCommand.java
- src/main/java/wellnus/reflection/GetCommand.java
- src/main/java/wellnus/reflection/ReflectionManager.java
- src/main/java/wellnus/reflection/ReturnCommand.java
Update `MainManager` to support the self reflection feature via `ReflectionManager`.
Had to change the `FEATURE_NAME` attribute for reflect's `Command` classes, @wenxin-c are you agreeable? This is meant as a common way for `MainManager` to activate feature `Manager`s while keeping the logic abstract(and encapsulated in the feature's `Manager`)
> Support reflect commands

- src/main/java/wellnus/reflection/GetCommand.java
- src/main/java/wellnus/reflection/SelfReflection.java
- src/test/java/wellnus/reflection/GetCommandTest.java
Fix missing constructor call to `SelfReflection` that leads to program crash when you call the `get` command of the self reflections feature.
A related issue that I feel the team should discuss is #85
> Fix crash in GetCommand of reflections feature

- src/main/java/wellnus/common/MainManager.java
Right now returning from a feature's `Manager` to `MainManager` results in an ugly invalid command message being printed on the user's screen, which is not intended behaviour.
Eliminate this ugly invalid command message to improve user experience.
> Fix unintended BadCommandException

- src/main/java/wellnus/reflection/ExitCommand.java
- src/main/java/wellnus/reflection/GetCommand.java
- src/main/java/wellnus/reflection/ReturnCommand.java
Fixes #98 
Adding ```return;``` in catch block after a BadCommandException is caught to return back to main loop. In this way, the ```execute()```method will not continue executing.
> Bug get reflect question parameter bug

- src/main/java/wellnus/exception/TokenizerException.java
- src/main/java/wellnus/storage/Tokenizer.java
Individual features all have different ways of converting state(of their `Manager`) into `String` representations, and from `String` representations back into the saved state. So the exact implementation of these operations can be left abstract.
That being said, we do want expect all implementations to have the same input and output(the same 'black box' representation of their operations), so all features shall provide the same method signatures for their `tokenize()` and `detokenize()` operations.
Hence, the need for a `Tokenizer` interface.
This closes #132.
> Define Tokenizer interface

- build.gradle
Fixes #141 
Enable assertions in ```build.gradle```
This is a weekly task required.
> Enable assertions for team repo

- src/main/java/wellnus/command/CommandParser.java
- src/test/java/wellnus/command/CommandParserTest.java
This fixes #100.
- Added trim functions to methods that handle argument extraction
> Ignore case for `CommandParser` arguments

- src/main/java/wellnus/atomichabit/command/HomeCommand.java
- src/main/java/wellnus/focus/command/HomeCommand.java
- src/main/java/wellnus/gamification/GamificationManager.java
- src/main/java/wellnus/gamification/command/HomeCommand.java
- src/main/java/wellnus/reflection/command/HomeCommand.java
Check for additional, unnecessary arguments given for `home` in atomic habits, gamification and focus timer features to make our application more robust.
Also make the error message for invalid home command in reflection feature more specific to help the user.
> Fix unreliable home commands

- src/main/java/wellnus/reflection/feature/QuestionList.java
- src/main/java/wellnus/storage/AtomicHabitTokenizer.java
- src/main/java/wellnus/storage/ReflectionTokenizer.java
`AtomicHabitTokenizer` and `ReflectionTokenizer` now complains when their data files exist but are empty, which is not actually an issue.
Implement checks so they stop complaining so much, which is ugly.
> Fix bogus Tokenizer Exceptions

- src/main/java/wellnus/command/ExitCommand.java
Stop allowing `exit` command to succeed when extra arguments are given
> Check `exit` command arguments

- src/main/java/wellnus/atomichabit/command/DeleteCommand.java
- src/main/java/wellnus/atomichabit/command/UpdateCommand.java
- src/main/java/wellnus/atomichabit/feature/AtomicHabitList.java
- src/main/java/wellnus/command/CommandParser.java
- src/main/java/wellnus/common/WellNusLogger.java
- src/main/java/wellnus/focus/command/ConfigCommand.java
- src/main/java/wellnus/focus/feature/FocusUi.java
- src/main/java/wellnus/reflection/command/FavoriteCommand.java
- src/main/java/wellnus/reflection/command/GetCommand.java
- src/main/java/wellnus/reflection/command/HomeCommand.java
- src/main/java/wellnus/reflection/command/LikeCommand.java
- src/main/java/wellnus/reflection/command/PrevCommand.java
- src/main/java/wellnus/reflection/command/UnlikeCommand.java
- src/main/java/wellnus/reflection/feature/QuestionList.java
- src/main/java/wellnus/reflection/feature/ReflectionManager.java
- src/main/java/wellnus/storage/ReflectionTokenizer.java
- src/main/java/wellnus/storage/Storage.java
- src/main/java/wellnus/ui/TextUi.java
Since logging currently prints directly to the user's screen, which is unsightly, let's redirect all logging in our app to a specific log file, `log/wellnus.log` relative to the runtime jar file.
Some basic features of this implementation:
-Entire app's logging will be saved inside this file, `log/wellnus.log`
-To preserve user's storage space, `log/wellnus.log` will be cleared on the next app run if it exceeds **5MB**
This closes #111 #257.
> Redirect logging to file

- src/main/java/wellnus/gamification/command/StatsCommand.java
Implement additional checks to ensure that extra arguments are not given to the `stats` command.
This catches bogus commands like `stats test` which now correctly throws a `BadCommandException`.
This fixes #279.
> Improve `gamif` `stats` command validation

- src/main/java/wellnus/storage/ReflectionTokenizer.java
- src/test/java/wellnus/tokenize/ReflectionTokenizerTest.java
Address the bug in reflect tokenizer where corrupted file is not overwritten when loaded
> add overwrite feature to the detokenizer

- docs/AboutUs.md
AboutUs Page currently points to a non-existent markdown page. Github pages actually generates a html file for each markdown in the docs folder, so switch to that URL instead.
Check that your PPPs fit within the page limit everyone!
This addresses #327.
> Fix AboutUs Page PPP URLs

- docs/UserGuide.md
- src/main/java/wellnus/atomichabit/command/DeleteCommand.java
- src/main/java/wellnus/atomichabit/command/HelpCommand.java
- src/main/java/wellnus/atomichabit/command/ListCommand.java
- src/main/java/wellnus/atomichabit/command/UpdateCommand.java
- src/main/java/wellnus/atomichabit/feature/AtomicHabitManager.java
- src/main/java/wellnus/command/HelpCommand.java
- src/main/java/wellnus/focus/command/CheckCommand.java
- src/main/java/wellnus/focus/command/ConfigCommand.java
- src/main/java/wellnus/focus/command/HelpCommand.java
- src/main/java/wellnus/focus/command/NextCommand.java
- src/main/java/wellnus/focus/command/ResumeCommand.java
- src/main/java/wellnus/focus/command/StopCommand.java
- src/main/java/wellnus/focus/feature/FocusManager.java
- src/main/java/wellnus/gamification/GamificationManager.java
- src/main/java/wellnus/gamification/command/HelpCommand.java
- src/main/java/wellnus/gamification/command/StatsCommand.java
- src/main/java/wellnus/reflection/command/FavoriteCommand.java
- src/main/java/wellnus/reflection/command/HelpCommand.java
- src/main/java/wellnus/reflection/command/LikeCommand.java
- src/main/java/wellnus/reflection/command/PrevCommand.java
- src/main/java/wellnus/reflection/command/UnlikeCommand.java
- src/main/java/wellnus/reflection/feature/QuestionList.java
- src/main/java/wellnus/reflection/feature/ReflectionManager.java
- src/test/java/wellnus/focus/command/ConfigCommandTest.java
This pr
- fixes #304 format of `help` features
- fixes #309 Standardise error message for gamif `stats`
- fixes #311 Inconsistent error message for reflect
- fixes #314 Question string
- fixes #316 on reflect and gamif error notes
- fixes #323 Inconsistent indentation for help and update user guide for help command
> Reflect error message and help command format bug fix

- src/main/java/wellnus/common/MainManager.java
- text-ui-test/EXPECTED.TXT
Extra space for error message printing.
> Remove extra space printed for MainManger when invalid command is given

- src/main/java/wellnus/atomichabit/command/UpdateCommand.java
Rename `e` to `indexOutOfBoundsException` to make the variable's purpose more obvious.
This fixes #130.
> Fix single-letter variable name

- docs/DeveloperGuide.md
Update Table of Contents after #381 added new subsections in the manual testing section
> Update DeveloperGuide Table of Contents
