src/main/java/seedu/duke/command/Command.java

Define a Command superclass that all of WellNus' commands shall extend so that we can guarantee basic functionality, particularly the `execute()` method for executing a specific Command.
This addresses #26.

Define Command superclass

---

src/main/java/seedu/duke/command/CommandParser.java

This fixes #32.
Ignore the main command by starting from one

Fix parser off by one error

---

src/main/java/seedu/duke/command/Command.java
src/main/java/seedu/duke/command/CommandParser.java
src/main/java/seedu/duke/exception/BadCommandException.java
src/main/java/seedu/duke/exception/WellNusException.java
src/main/java/seedu/duke/manager/Manager.java
src/test/java/seedu/duke/command/CommandParserTest.java

This pr closes #38 
1. Added an `exception` package to WellNus
2. Added WellNusException class which is a superclass for all the exceptions
3. Refactor BadCommandException to adjust to the new change

Add exception package and add superclass WellNusException

---

src/main/java/seedu/duke/ui/TextUi.java
src/test/java/seedu/duke/ui/TextUiTest.java

Fixes #47 
This improve UI print error method to include both error message and additional notes for user.
Error messages and additional notes will be printed on separate lines with labels for each.
Additional context
Additional notes serve to help users figure out the causes of exception and give them suggestions on what should be the correct input.

Improve UI print error method

---

.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/user-story-features.md

Enhancements are meant to be for changes to existing features, while features are meant to be new additions to WellNus. So the former deserves to be its own issue category.

Add GitHub issue template for 'Enhancements' category

---

src/main/java/seedu/duke/atomichabit/command/Command.java
src/main/java/seedu/duke/atomichabit/command/UpdateCommand.java
src/main/java/seedu/duke/atomichabit/feature/AtomicHabit.java
src/main/java/seedu/duke/atomichabit/feature/AtomicHabitList.java
src/main/java/seedu/duke/atomichabit/feature/AtomicHabitManager.java
src/test/java/seedu/duke/atomichabit/AtomicHabitTest.java

Resolves #23 
Add a new feature that allows users to update the count of atomic habits.
Things to do:
1. Add test cases

Feature-Update Atomic Habit 

---

src/main/java/seedu/duke/manager/Manager.java

This closes #63 .
- Removed supportedManagers from manager as per group disussion

Remove supportedManagers from Manager

---

src/main/java/wellnus/manager/Manager.java

This is part of the effort by #62 .
Add assertion checks to Manager

Add defensive assertion checks to Manager

---

src/main/java/wellnus/command/CommandParser.java

This is part of efforts in #62 and #56.
- Added nullcheck assertions
- Added INFO level logging on thrown exceptions. These logs are meant to help with tracking and debugging.
This is especially useful in case a feature does not gracefully handle the thrown exception or
encounters another error later on (e.g. empty input gets passed to another function that causes runtime error)

Add assertions and logging to Command Parser

---

src/main/java/wellnus/atomichabit/command/AddCommand.java
src/main/java/wellnus/atomichabit/feature/AtomicHabitManager.java

Added ascii art for atomic habit logo inside `AtomicHabitManager` and added additional assertions.

Add atomic habits logo and additional assertions

---

src/main/java/wellnus/reflection/GetCommand.java
src/main/java/wellnus/reflection/HomeCommand.java
src/main/java/wellnus/reflection/ReflectionManager.java
src/main/java/wellnus/reflection/ReflectionQuestion.java
src/main/java/wellnus/reflection/SelfReflection.java
src/test/java/wellnus/reflection/ReflectionManagerTest.java
src/test/java/wellnus/reflection/ReflectionQuestionTest.java
src/test/java/wellnus/reflection/SelfReflectionTest.java

This fixes checkstyle violations for: 
main packages: ```reflection```
test packages: ```ReflectionManager```, ```ReflectionQuestion```, ```SelfReflection```

Self reflection checkstyle fixes

---

src/main/java/wellnus/common/MainManager.java
src/main/java/wellnus/exception/AtomicHabitException.java
src/main/java/wellnus/exception/BadCommandException.java
src/main/java/wellnus/exception/WellNusException.java
src/main/java/wellnus/manager/Manager.java
src/test/java/wellnus/command/CommandParserTest.java
src/test/java/wellnus/ui/TextUiTest.java

- Stylistic changes to adhere to commonly agreed format

Common Files Checkstyle Fixes

---

src/main/java/wellnus/atomichabit/feature/AtomicHabit.java
src/main/java/wellnus/atomichabit/feature/AtomicHabitList.java
src/main/java/wellnus/atomichabit/feature/AtomicHabitManager.java
src/test/java/wellnus/reflection/GetCommandTest.java
src/test/java/wellnus/reflection/HomeCommandTest.java

Fixed allocated check style issues.

AtomicHabit Feature  checkstyle fixes

---

build.gradle

See [IntelliJ's guide](https://www.jetbrains.com/help/idea/getting-started-with-gradle.html#deploy_gradle) on building jar with gradle for details of how to make use of this configuration.

Setup gradle for building jar

---

src/main/java/wellnus/storage/Tokenizer.java

On implementation, some changes were proposed for the common `Tokenizer` methods, which made sense.
This PR provides them to aid in implementing the actual feature `Tokenizer`s.

Update Tokenizer interface

---

docs/DeveloperGuide.md
docs/diagrams/style.puml

Common information of developer guide has been filled up. Each of us can fill in our respective parts for user story and design UML. Refer to AB-3 developer guide for reference: https://se-education.org/addressbook-level3/DeveloperGuide.html
**This should be done by Tuesday night.**

Setup developer guide skeleton

---

src/main/java/wellnus/atomichabit/feature/AtomicHabitManager.java
src/main/java/wellnus/command/ExitCommand.java
src/main/java/wellnus/command/HelpCommand.java
src/main/java/wellnus/focus/feature/FocusManager.java
src/main/java/wellnus/reflection/ReflectionManager.java

- Added support for `help [command-to-query]` in the main manager's `HelpCommand`
- Updated regressive issues

Add descriptive commands for `Help` 

---

src/main/java/wellnus/gamification/GamificationManager.java

- bugfix for gamif getting terminated when wrong commands are input

Fix Exiting from `gamif` bug

---

src/main/java/wellnus/atomichabit/feature/AtomicHabitList.java
src/main/java/wellnus/storage/AtomicHabitTokenizer.java
src/main/java/wellnus/storage/Storage.java
text-ui-test/EXPECTED.TXT

Added checkfileexists method inside storage class.
Removed logger printing and addressed printing of exception at the top.

Address logger error and unintended output

---

src/main/java/wellnus/gamification/GamificationManager.java

This is to fix gamification styling error.

Fix gamification styling error

---

docs/UserGuide.md

-Updated Q&A section
-Improved gamification feature section

User Guide improvements

---

src/main/java/wellnus/reflection/feature/QuestionList.java
src/main/java/wellnus/reflection/feature/ReflectionManager.java

This is to fix self reflection corrupt file crash bug. This is because arrayList and hash set is not properly initialised if there is exception due to tokenizer. The self reflection logo is also changed to to a smaller logo, the previous one was too big so some parts will be cut off.

Fix reflect corrupt file crash

---

src/main/java/wellnus/atomichabit/command/HelpCommand.java
src/main/java/wellnus/command/HelpCommand.java
src/main/java/wellnus/focus/command/HelpCommand.java
src/main/java/wellnus/gamification/command/HelpCommand.java
src/main/java/wellnus/reflection/command/HelpCommand.java

Add missing javadoc for help command

---

src/main/java/wellnus/atomichabit/command/AddCommand.java
src/main/java/wellnus/atomichabit/command/DeleteCommand.java
src/main/java/wellnus/atomichabit/command/HelpCommand.java
src/main/java/wellnus/atomichabit/command/HomeCommand.java
src/main/java/wellnus/atomichabit/command/ListCommand.java
src/main/java/wellnus/atomichabit/command/UpdateCommand.java
src/main/java/wellnus/atomichabit/feature/AtomicHabitManager.java
src/main/java/wellnus/atomichabit/feature/AtomicHabitUi.java
src/main/java/wellnus/focus/feature/FocusManager.java
src/main/java/wellnus/focus/feature/FocusUi.java
src/test/java/wellnus/atomichabit/AtomicHabitTest.java

Updated AtomicHabit with AtomicHabitUi to have unique line separator.
Updated Focus timer Ui printing message and included Focus Logo.
This resolves #275, #276.

Enhancement unique separator habits

---

docs/UserGuide.md

Mainly rephrasing sentences to make them clearer and fixing some inconsistencies in formatting. Should look more professional and error-free now.

Improve UserGuide

---

docs/UserGuide.md
src/main/java/wellnus/reflection/command/HelpCommand.java

This is to fix UG reflection regression errors and some other details.

Fix user guide regression errors

---

docs/UserGuide.md

Answer some more common questions and remove some questions that are already answered in previous sections of the UserGuide.

Improve FAQ section of UserGuide

---

src/main/java/wellnus/gamification/GamificationManager.java
src/main/java/wellnus/gamification/command/HelpCommand.java
src/main/java/wellnus/gamification/util/GamificationUi.java
src/main/java/wellnus/ui/TextUi.java

Make `GamificationUi` inherit from `TextUi` and refactor the `gamification` subpackage classes to switch from using `TextUi` to `GamificationUi` now to fulfil OOP.

Improve Gamification Implementation

---

src/main/java/wellnus/command/CommandParser.java

This fixes #310 
- Add strip logic to payload

Add strip logic to fix payload issue

---

docs/team/wenxin-c.md

This is to further summarize wenxin's ppp

Document shorten ppp

---

src/test/java/wellnus/ui/TextUiTest.java

This is to remove magic literal for UI test

Remove magic literal for UI test

---

src/test/java/wellnus/reflection/command/FavoriteCommandTest.java
src/test/java/wellnus/reflection/command/GetCommandTest.java
src/test/java/wellnus/reflection/command/HomeCommandTest.java
src/test/java/wellnus/reflection/command/LikeCommandTest.java
src/test/java/wellnus/reflection/command/PrevCommandTest.java
src/test/java/wellnus/reflection/command/UnlikeCommandTest.java
src/test/java/wellnus/reflection/feature/QuestionListTest.java
src/test/java/wellnus/reflection/feature/RandomNumberGeneratorTest.java
src/test/java/wellnus/reflection/feature/ReflectionManagerTest.java
src/test/java/wellnus/reflection/feature/ReflectionQuestionTest.java
src/test/java/wellnus/ui/TextUiTest.java

This is to add javadoc for textui and reflect junit tests.

Add test javadoc for ui and reflect

---

docs/team/wenxin-c.md

This is to fullfil page break and limit

Summarise wenxin's PPP

---

docs/UserGuide.md
src/main/java/wellnus/common/MainManager.java
src/main/java/wellnus/reflection/feature/QuestionList.java

Remove `TODO` comments now that we're ending this project. And fix a minor issue in UserGuide.

Cleanup code and UserGuide

---

docs/team/wenxin-c.md

Adjust PPP page break

---

docs/team/haoyangw.md

Update PPP with my contributions to bug fixing, DG, UG and JUnit Testing

Update contributions in haoyangw's PPP

---

src/main/java/wellnus/common/MainManager.java
src/test/java/wellnus/common/MainManagerTest.java

Verify that important behaviours of `MainManager` function as intended and expected.

Write JUnit tests for `MainManager`

---

docs/team/yongbinwang.md

Update PPP for formatting error

---

docs/team/haoyangw.md

Fix typo and link haoyangw/ped to be safe.

Fix typo in haoyangw's PPP

---

docs/DeveloperGuide.md

Update test cases' outputs after our recent standardisation of error messages and new feature separators.

Update DeveloperGuide test cases' outputs

---

docs/DeveloperGuide.md

Document add user story dg

---

docs/DeveloperGuide.md

Provide test cases for each feature we have to help users understand how to test our app.

More DG test cases

---

docs/DeveloperGuide.md

Indent code blocks to fix list indices in DeveloperGuide

Fix list indices in DeveloperGuide
